#pragma once
#include "pch.h"

namespace itemlist
{
    const auto accessories =
    {
        "Accessory_AT_1|Attack Pendant",
        "Accessory_AT_2|Attack Pendant+1",
        "Accessory_AT_3|Attack Pendant+2",
        "Accessory_defense_1|Defense Pendant",
        "Accessory_defense_2|Defense Pendant +1",
        "Accessory_defense_3|Defense Pendant +2",
        "Accessory_HeatResist_1|Heat Resistant Underwear",
        "Accessory_HeatResist_2|Heat Resistant Underwear+1",
        "Accessory_HeatResist_3|Heat Resistant Underwear+2",
        "Accessory_HP_1|Life Pendant",
        "Accessory_HP_2|Life Pendant+1",
        "Accessory_HP_3|Life Pendant+2",
        "Accessory_WorkSpeed_1|Pendant Of Diligence",
        "Accessory_WorkSpeed_2|Pendant Of Diligence+1",
        "Accessory_WorkSpeed_3|Pendant Of Diligence+2",
        "Accessory_AquaResist_1|Ring Of Water Resistance",
        "Accessory_AquaResist_2|Ring Of Water Resistance+1",
        "Accessory_AquaResist_3|Ring Of Water Resistance+2",
        "Accessory_DarkResist_1|Ring Of Dark Resistance",
        "Accessory_DarkResist_2|Ring Of Dark Resistance+1",
        "Accessory_DarkResist_3|Ring Of Dark Resistance+2",
        "Accessory_DragonResist_1|Ring Of Dragon Resistance",
        "Accessory_DragonResist_2|Ring Of Dragon Resistance+1",
        "Accessory_DragonResist_3|Ring Of Dragon Resistance+2",
        "Accessory_EarthResist_1|Ring Of Earth Resistance",
        "Accessory_EarthResist_2|Ring Of Earth Resistance+1",
        "Accessory_EarthResist_3|Ring Of Earth Resistance+2",
        "Accessory_FireResist_1|Ring Of Flame Resistance",
        "Accessory_FireResist_2|Ring Of Flame Resistance+1",
        "Accessory_FireResist_3|Ring Of Flame Resistance+2",
        "Accessory_IceResist_1|Ring Of Ice Resistance",
        "Accessory_IceResist_2|Ring Of Ice Resistance+1",
        "Accessory_IceResist_3|Ring Of Ice Resistance+2",
        "Accessory_LeafResist_1|Ring Of Grass Resistance",
        "Accessory_LeafResist_2|Ring Of Grass Resistance+1",
        "Accessory_LeafResist_3|Ring Of Grass Resistance+2",
        "Accessory_NormalResist_1|Ring Of Resistance",
        "Accessory_NormalResist_2|Ring Of Resistance+1",
        "Accessory_NormalResist_3|Ring Of Resistance+2",
        "Accessory_ThunderResist_1|Ring Of Lightning Resistance",
        "Accessory_ThunderResist_2|Ring Of Lightning Resistance+1",
        "Accessory_ThunderResist_3|Ring Of Lightning Resistance+2",
        "Accessory_CoolResist_1|Thermal Underwear",
        "Accessory_CoolResist_2|Thermal Underwear+1",
        "Accessory_CoolResist_3|Thermal Underwear+2"
    };

    const auto ammo =
    {
        "AssaultRifleBullet|Assault Rifle Ammo",
        "Arrow|Arrow",
        "RoughBullet|Coarse Ammo",
        "InkBullet|Decal Ink",
        "Arrow_Fire|Fire Arrow",
        "HandgunBullet|Handgun Ammo",
        "LaserBullet|Laser Ammo",
        "MachingunBullet|Machine Gun Ammo",
        "MagnumBullet|Magnum Ammo",
        "Arrow_Poison|Poison Arrow",
        "ExplosiveBullet|Rocket Ammo",
        "RifleBullet|Rifle Ammo",
        "ShotgunBullet|Shotgun Shells"
    };

    const auto armor =
    {
        "AutoMealPouch_Tier2|Average Feed Bag",
        "ClothArmor|Cloth Outfit(Common)",
        "ClothArmor_2|Cloth Outfit(Uncommon)",
        "ClothArmor_3|Cloth Outfit(Rare)",
        "ClothArmor_4|Cloth Outfit(Epic)",
        "ClothArmor_5|Cloth Outfit(Legendary)",
        "CopperArmorCold|Cold Resistant Metal Armor(Common)",
        "CopperArmorCold_2|Cold Resistant Metal Armor(Uncommon)",
        "CopperArmorCold_3|Cold Resistant Metal Armor(Rare)",
        "CopperArmorCold_4|Cold Resistant Metal Armor(Epic)",
        "CopperArmorCold_5|Cold Resistant Metal Armor(Legendary)",
        "FurArmorCold|Cold Resistant Pelt Armor(Common)",
        "FurArmorCold_2|Cold Resistant Pelt Armor(Uncommon)",
        "FurArmorCold_3|Cold Resistant Pelt Armor(Rare)",
        "FurArmorCold_4|Cold Resistant Pelt Armor(Epic)",
        "FurArmorCold_5|Cold Resistant Pelt Armor(Legendary)",
        "IronArmorCold|Cold Resistant Refined Metal Armor(Common)",
        "IronArmorCold_2|Cold Resistant Refined Metal Armor(Uncommon)",
        "IronArmorCold_3|Cold Resistant Refined Metal Armor(Rare)",
        "IronArmorCold_4|Cold Resistant Refined Metal Armor(Epic)",
        "IronArmorCold_5|Cold Resistant Refined Metal Armor(Legendary)",
        "StealArmorCold|Cold Resistant Pal Metal Armor(Common)",
        "StealArmorCold_2|Cold Resistant Pal Metal Armor(Uncommon)",
        "StealArmorCold_3|Cold Resistant Pal Metal Armor(Rare)",
        "StealArmorCold_4|Cold Resistant Pal Metal Armor(Epic)",
        "StealArmorCold_5|Cold Resistant Pal Metal Armor(Legendary)",
        "FurHelmet|Feathered Hair Band(Common)",
        "FurHelmet_2|Feathered Hair Band(Uncommon)",
        "FurHelmet_3|Feathered Hair Band(Rare)",
        "FurHelmet_4|Feathered Hair Band(Epic)",
        "FurHelmet_5|Feathered Hair Band(Legendary)",
        "AutoMealPouch_Tier5|Giant Feed Bag",
        "CopperArmorHeat|Heat Resistant Metal Armor(Common)",
        "CopperArmorHeat_2|Heat Resistant Metal Armor(Uncommon)",
        "CopperArmorHeat_3|Heat Resistant Metal Armor(Rare)",
        "CopperArmorHeat_4|Heat Resistant Metal Armor(Epic)",
        "CopperArmorHeat_5|Heat Resistant Metal Armor(Legendary)",
        "FurArmorHeat|Heat Resistant Pelt Armor(Common)",
        "FurArmorHeat_2|Heat Resistant Pelt Armor(Uncommon)",
        "FurArmorHeat_3|Heat Resistant Pelt Armor(Rare)",
        "FurArmorHeat_4|Heat Resistant Pelt Armor(Epic)",
        "FurArmorHeat_5|Heat Resistant Pelt Armor(Legendary)",
        "AutoMealPouch_Tier4|Huge Feed Bag",
        "IronArmorHeat|Heat Resistant Refined Metal Armor(Common)",
        "IronArmorHeat_2|Heat Resistant Refined Metal Armor(Uncommon)",
        "IronArmorHeat_3|Heat Resistant Refined Metal Armor(Rare)",
        "IronArmorHeat_4|Heat Resistant Refined Metal Armor(Epic)",
        "IronArmorHeat_5|Heat Resistant Refined Metal Armor(Legendary)",
        "StealArmorHeat|Heat Resistant Pal Metal Armor(Common)",
        "StealArmorHeat_2|Heat Resistant Pal Metal Armor(Uncommon)",
        "StealArmorHeat_3|Heat Resistant Pal Metal Armor(Rare)",
        "StealArmorHeat_4|Heat Resistant Pal Metal Armor(Epic)",
        "StealArmorHeat_5|Heat Resistant Pal Metal Armor(Legendary)",
        "AutoMealPouch_Tier3|Large Feed Bag",
        "CopperArmor|Metal Armor(Common)",
        "CopperArmor_2|Metal Armor(Uncommon)",
        "CopperArmor_3|Metal Armor(Rare)",
        "CopperArmor_4|Metal Armor(Epic)",
        "CopperArmor_5|Metal Armor(Legendary)",
        "CopperHelmet|Metal Helm(Common)",
        "CopperHelmet_2|Metal Helm(Uncommon)",
        "CopperHelmet_3|Metal Helm(Rare)",
        "CopperHelmet_4|Metal Helm(Epic)",
        "CopperHelmet_5|Metal Helm(Legendary)",
        "FurArmor|Pelt Armor(Common)",
        "FurArmor_2|Pelt Armor(Uncommon)",
        "FurArmor_3|Pelt Armor(Rare)",
        "FurArmor_4|Pelt Armor(Epic)",
        "FurArmor_5|Pelt Armor(Legendary)",
        "StealArmor|Pal Metal Armor(Common)",
        "StealArmor_2|Pal Metal Armor(Uncommon)",
        "StealArmor_3|Pal Metal Armor(Rare)",
        "StealArmor_4|Pal Metal Armor(Epic)",
        "StealArmor_5|Pal Metal Armor(Legendary)",
        "StealHelmet|Pal Metal Helm(Common)",
        "StealHelmet_2|Pal Metal Helm(Uncommon)",
        "StealHelmet_3|Pal Metal Helm(Rare)",
        "StealHelmet_4|Pal Metal Helm(Epic)",
        "StealHelmet_5|Pal Metal Helm(Legendary)",
        "IronArmor|Refined Metal Armor(Common)",
        "IronArmor_2|Refined Metal Armor(Uncommon)",
        "IronArmor_3|Refined Metal Armor(Rare)",
        "IronArmor_4|Refined Metal Armor(Epic)",
        "IronArmor_5|Refined Metal Armor(Legendary)",
        "IronHelmet|Refined Metal Helm(Common)",
        "IronHelmet_2|Refined Metal Helm(Uncommon)",
        "IronHelmet_3|Refined Metal Helm(Rare)",
        "IronHelmet_4|Refined Metal Helm(Epic)",
        "IronHelmet_5|Refined Metal Helm(Legendary)",
        "AutoMealPouch_Tier1|Small Feed Bag",
        "ClothArmorCold|Tundra Outfit(Common)",
        "ClothArmorCold_2|Tundra Outfit(Uncommon)",
        "ClothArmorCold_3|Tundra Outfit(Rare)",
        "ClothArmorCold_4|Tundra Outfit(Epic)",
        "ClothArmorCold_5|Tundra Outfit(Legendary)",
        "ClothArmorHeat|Tropical Outfit(Common)",
        "ClothArmorHeat_2|Tropical Outfit(Uncommon)",
        "ClothArmorHeat_3|Tropical Outfit(Rare)",
        "ClothArmorHeat_4|Tropical Outfit(Epic)",
        "ClothArmorHeat_5|Tropical Outfit(Legendary)",
    };

    const auto craftingmaterials =
    {
        "PalCrystal_Ex|Ancient Civilization Parts",
        "Bone|Bone",
        "Poppy|Beautiful Flowers",
        "CrudeOil|Crude Oil",
        "Claws|Claws",
        "Cloth|Cloth",
        "Coal|Coal",
        "Cement|Cement",
        "Charcoal|Charcoal",
        "CarbonFiber|Carbon Fiber",
        "MachineParts2|Circuit Board",
        "ElectricOrgan|Electric Organ",
        "Flour|Flour",
        "Fiber|Fiber",
        "FireOrgan|Flame Organ",
        "GunPowder2|Gunpowder",
        "PalItem_PlantSlime|Gumoss Leaf",
        "Cloth2|High Quality Cloth",
        "PalOil|High Quality Pal Oil",
        "Horn|Horn",
        "CopperIngot|Ingot",
        "IceOrgan|Ice Organ",
        "PalItem_CatMage|Katress Hair",
        "Leather|Leather",
        "MachineParts|Nails",
        "CopperOre|Ore",
        "PalFluid|Pal Fluids",
        "Polymer|Polymer",
        "Pal_crystal_L|Paldium Clump",
        "Pal_crystal_S|Paldium Fragment",
        "StealIngot|Pal Metal Ingot",
        "Quartz|Pure Quartz",
        "PalItem_CaptainPenguin|Punking Plume",
        "IronIngot|Refined Ingot",
        "Stone|Stone",
        "Sulfur|Sulfur",
        "PalItem_ColorfulBird|Tocotoco Feather",
        "Venom|Venom Gland",
        "Wood|Wood",
        "Wool|Wool",
		"SkyIslandOre|Soralite",
		"WorldTreeOre|Paloxite",
    };

    const auto eggs =
    {
        "PalEgg_Dark_01|Dark Egg",
        "PalEgg_Dark_02|Dark Egg(2)",
        "PalEgg_Dark_03|Large Dark Egg",
        "PalEgg_Dark_04|Large Dark Egg(2)",
        "PalEgg_Dark_05|Huge Dark Egg",
        "PalEgg_Dragon_01|Dragon Egg",
        "PalEgg_Dragon_02|Dragon Egg(2)",
        "PalEgg_Dragon_03|Large Dragon Egg",
        "PalEgg_Dragon_04|Large Dragon Egg(2)",
        "PalEgg_Dragon_05|Huge Dragon Egg",
        "PalEgg_Earth_01|Rocky Egg",
        "PalEgg_Earth_02|Rough Egg(2)",
        "PalEgg_Earth_03|Large Rocky Egg",
        "PalEgg_Earth_04|Large Rocky Egg(2)",
        "PalEgg_Earth_05|Huge Rocky Egg",
        "PalEgg_Electricity_01|Electric Egg",
        "PalEgg_Electricity_02|Electric Egg(2)",
        "PalEgg_Electricity_03|Large Electric Egg",
        "PalEgg_Electricity_04|Large Electric Egg(2)",
        "PalEgg_Electricity_05|Huge Electric Egg",
        "PalEgg_Fire_01|Scorching Egg",
        "PalEgg_Fire_02|Scorching Egg(2)",
        "PalEgg_Fire_03|Large Scorching Egg",
        "PalEgg_Fire_04|Large Scorching Egg",
        "PalEgg_Fire_05|Huge Scorching Egg",
        "PalEgg_Ice_01|Frozen Egg",
        "PalEgg_Ice_02|Frozen Egg(2)",
        "PalEgg_Ice_03|Large Frozen Egg",
        "PalEgg_Ice_04|Large Frozen Egg(2)",
        "PalEgg_Ice_05|Huge Frozen Egg",
        "PalEgg_Leaf_01|Verdant Egg",
        "PalEgg_Leaf_02|Verdant Egg(2)",
        "PalEgg_Leaf_03|Large Verdant Egg",
        "PalEgg_Leaf_04|Large Verdant Egg(2)",
        "PalEgg_Leaf_05|Huge Verdant Egg",
        "PalEgg_Normal_01|Common Egg",
        "PalEgg_Normal_02|Common Egg(2)",
        "PalEgg_Normal_03|Large Common Egg",
        "PalEgg_Normal_04|Large Common Egg(2)",
        "PalEgg_Normal_05|Huge Common Egg",
        "PalEgg_Water_01|Damp Egg",
        "PalEgg_Water_02|Damp Egg(2)",
        "PalEgg_Water_03|Large Damp Egg",
        "PalEgg_Water_04|Large Damp Egg(2)",
        "PalEgg_Water_05|Huge Damp Egg"
    };

    const auto food =
    {
        "BLT|Burrito",
        "BakedMeat_LazyCatfish|Broiled Dumund",
        "BakedMeat_SakuraSaurus|Broncherry Rib Roast",
        "BakedMushroom|Baked Mushrooms",
        "Baked_Berries|Baked Berries",
        "MeatSauce|Bolognese Sauce",
        "Meat_SakuraSaurus|Broncherry Meat",
        "Pan|Bread",
        "Cake|Cake",
        "CheeseBurger|Cheeseburger",
        "ChickenSaute|Chikipi Saute",
        "Carbonara|Carbonara",
        "Meat_BerryGoat|Caprity Meat",
        "Meat_ChickenPal|Chikipi Poultry",
        "Sweet|Cotton Candy",
        "Chowder|Dumund Chowder",
        "Egg|Egg",
        "DeerLocoMoco|Eikthyrdeer Loco Moco",
        "DeerStew|Eikthyrdeer Stew",
        "Meat_Deer|Eikthyrdeer Venison",
        "FriedChicken|Fried Chikipi",
        "FriedEggs|Fried Eggs",
        "FriedKelpie|Fried Kepsea",
        "BakedMeat_ChickenPal|Grilled Chikipi",
        "BakedMeat_Eagle|Grilled Galeclaw",
        "BakedMeat_Kelpie|Grilled Kelpsea",
        "Meat_Eagle|Galeclaw Poultry",
        "GrilledMeat|Grilled Meat",
        "GenghisKhan|Grilled Lamball",
        "BakedMeat_BerryGoat|Herb Roasted Caprity",
        "Honey|Honey",
        "HotDog|Hot Dog",
        "HotMilk|Hot Milk",
        "GrilledSheepHerbs|Herb Roasted Lamball",
        "Hamburger|Hamburger",
        "JamBun|Jam-filled Bun",
        "BakedMeat_SheepBall|Lamball Kebab",
        "Meat_SheepBall|Lamball Mutton",
        "Lettuce|Lettuce",
        "BakedMeat_CowPal|Moazzarina Steak",
        "BakedMeat_GrassMammoth|Mammorest Steak",
        "CheeseBurger_2|Mozzarina Cheeseburger",
        "Meat_CowPal|Mozzarina Meat",
        "Meat_GrassMammoth|Mammorest Meat",
        "Hamburger_2|Mozzarina Hamburger",
        "Milk|Milk",
        "MarinatedMushrooms|Marinated Mushrooms",
        "MushroomSoup|Mushroom Soup",
        "Mushroom|Mushroom",
        "Omelet|Omelet",
        "Pancake|Pancake",
        "Pizza|Pizza",
        "BaconEggs|Rushoar Bacon 'n' Eggs",
        "BakedMeat_Boar|Roast Rushoar",
        "BakedMeat_Deer|Roast Eikthyrdeer",
        "BakedMeat_IceDeer|Roast Reindrix",
        "Meat_Boar|Roshoar Pork",
        "Meat_IceDeer|Reindrix Venison",
        "Meat_Kelpie|Raw Kelpsea",
        "Meat_LazyCatfish|Raw Dumund",
        "Meat|Raw Meat",
        "HotDog_2|Rushoar Hot Dog",
        "StewedIceDeer|Reindrix Stew",
        "Berries|Red Wild Berries",
        "Eaglestew|Stewed Galeclaw",
        "FriedVegetables|Stir-fried Veggies",
        "Salad|Salad",
        "MushroomStew|Stewed Mushrooms",
        "Tomato|Tomato",
        "Wheat|Wheat"
    };

    const auto hats =
    {
        "Head012|Bowler Hat(Common)",
        "Head012_2|Bowler Hat(Uncommon)",
        "Head012_3|Bowler Hat(Rare)",
        "Head012_4|Bowler Hat(Epic)",
        "Head012_5|Bowler Hat(Legendary)",
        "Head009|Explorer Cap(Common)",
        "Head009_2|Explorer Cap(Uncommon)",
        "Head009_3|Explorer Cap(Rare)",
        "Head009_4|Explorer Cap(Epic)",
        "Head009_5|Explorer Cap(Legendary)",
        "Head011|Farming Hat(Common)",
        "Head011_2|Farming Hat(Uncommon)",
        "Head011_3|Farming Hat(Rare)",
        "Head011_4|Farming Hat(Epic)",
        "Head011_5|Farming Hat(Legendary)",
        "Head002|Golden Crown(Common)",
        "Head002_2|Golden Crown(Uncommon)",
        "Head002_3|Golden Crown(Rare)",
        "Head002_4|Golden Crown(Epic)",
        "Head002_5|Golden Crown(Legendary)",
        "Head010|Graduation Cap(Common)",
        "Head010_2|Graduation Cap(Uncommon)",
        "Head010_3|Graduation Cap(Rare)",
        "Head010_4|Graduation Cap(Epic)",
        "Head010_5|Graduation Cap(Legendary)",
        "Head014|Grinning Tocotoco Cap(Common)",
        "Head014_2|Grinning Tocotoco Cap(Uncommon)",
        "Head014_3|Grinning Tocotoco Cap(Rare)",
        "Head014_4|Grinning Tocotoco Cap(Epic)",
        "Head014_5|Grinning Tocotoco Cap(Legendary)",
        "Head015|Gusmoss Cap(Common)",
        "Head015_2|Gusmoss Cap(Uncommon)",
        "Head015_3|Gusmoss Cap(Rare)",
        "Head015_4|Gusmoss Cap(Epic)",
        "Head015_5|Gusmoss Cap(Legendary)",
        "Head006|Helmet(Common)",
        "Head006_2|Helmet(Uncommon)",
        "Head006_3|Helmet(Rare)",
        "Head006_4|Helmet(Epic)",
        "Head006_5|Helmet(Legendary)",
        "Head017|Katress Cap(Common)",
        "Head017_2|Katress Cap(Uncommon)",
        "Head017_3|Katress Cap(Rare)",
        "Head017_4|Katress Cap(Epic)",
        "Head017_5|Katress Cap(Legendary)",
        "Head003|Long-eared Headband(Common)",
        "Head003_2|Long-eared Headband(Uncommon)",
        "Head003_3|Long-eared Headband(Rare)",
        "Head003_4|Long-eared Headband(Epic)",
        "Head003_5|Long-eared Headband(Legendary)",
        "Head001|Monarch's Crown(Common)",
        "Head001_2|Monarch's Crown(Uncommon)",
        "Head001_3|Monarch's Crown(Rare)",
        "Head001_4|Monarch's Crown(Epic)",
        "Head001_5|Monarch's Crown(Legendary)",
        "Head016|Penking Cap(Common)",
        "Head016_2|Penking Cap(Uncommon)",
        "Head016_3|Penking Cap(Rare)",
        "Head016_4|Penking Cap(Epic)",
        "Head016_5|Penking Cap(Legendary)",
        "Head005|Soft Hat(Common)",
        "Head005_2|Soft Hat(Uncommon)",
        "Head005_3|Soft Hat(Rare)",
        "Head005_4|Soft Hat(Epic)",
        "Head005_5|Soft Hat(Legendary)",
        "Head007|Silk Hat(Common)",
        "Head007_2|Silk Hat(Uncommon)",
        "Head007_3|Silk Hat(Rare)",
        "Head007_4|Silk Hat(Epic)",
        "Head007_5|Silk Hat(Legendary)",
        "Head008|Tricorne(Common)",
        "Head008_2|Tricorne(Uncommon)",
        "Head008_3|Tricorne(Rare)",
        "Head008_4|Tricorne(Epic)",
        "Head008_5|Tricorne(Legendary)",
        "Head013|Tocotoco Cap(Common)",
        "Head013_2|Tocotoco Cap(Uncommon)",
        "Head013_3|Tocotoco Cap(Rare)",
        "Head013_4|Tocotoco Cap(Epic)",
        "Head013_5|Tocotoco Cap(Legendary)",
        "Head004|Witch Hat(Common)",
        "Head004_2|Witch Hat(Uncommon)",
        "Head004_3|Witch Hat(Rare)",
        "Head004_4|Witch Hat(Epic)",
        "Head004_5|Witch Hat(Legendary)"
    };

    const auto medicine =
    {
        "LuxuryMedicines|High Grade Medical Supplies",
        "Herbs|Low Quality Medical Supplies",
        "Medicines|Medical Supplies",
        "MindControlDrug|Mind Control Meds",
        "StatusPointResetSan|Memory Wiping Medicine",
        "Narcotic|Strange Juice",
        "Opium|Suspicious Juice"
    };

    const auto other =
    {
        "Unko_S|Dung",
        "TechnologyBook_G3|Future Technical Manual",
        "TechnologyBook_G1|High Grade Technical Manual",
        "Unko_L|Huge Dung Pile",
        "TechnologyBook_G2|Innovative Technical Manual",
        "PalUpgradeStone3|Large Pal Soul",
        "Relic|Lifmunk Effigy",
        "PalUpgradeStone2|Medium Pal Soul",
        "PalItem_ToSell_01|Precious Dragon Stone",
        "PalItem_ToSell_02|Precious Plume",
        "PalItem_ToSell_03|Precious Entrails",
        "PalItem_ToSell_04|Precious Claw",
        "PalItem_ToSell_05|Precious Pelt",
        "PalUpgradeStone|Small Pal Soul"
    };

    const auto palspheres =
    {
        "PalSphere_Giga|Giga Sphere",
        "PalSphere_Tera|Hyper Sphere",
        "PalSphere_Legend|Legendary Sphere",
        "PalSphere_Mega|Mega Sphere",
        "PalSphere|Pal Sphere",
        "PalSphere_Robbery|Radar Sphere",
        "PalSphere_Master|Ultra Sphere",
		"PalSphere_Ultimate|Ultimate Sphere",
		"PalSphere_Exotic|Exotic Sphere",
		"PalSphere_Ancient_1|Sol Sphere",
		"PalSphere_Ancient_2|Ancient Sphere",
    };
	
	// NOTE: SphereModule items aren't backed by a dedicated UClass in the SDK dump,
    // so these IDs are inferred from their icon texture names (e.g.
    // T_itemicon_SphereModule_Heavy.webp -> SphereModule_Heavy), the same pattern
    // every other Sphere/Weapon ID in this file already follows. One is flagged
    // below as uncertain - verify in-game before relying on it.
    const auto spheremodules =
    {
        "SphereModule_Heavy|Heavy Weight Module",
        "SphereModule_Curve|Curve Module",
        "SphereModule_Spiper|Sniper Module",           // NOTE: icon asset is misspelled "Spiper" not "Sniper" - this looks like an actual dev typo baked into the asset name, so the StaticItemId is likely "SphereModule_Spiper" too, but verify with GetInventorySlotOverview() after spawning
        "SphereModule_Curve2|Slider Module",
        "SphereModule_Sniper2|Sniper Module II",
        "SphereModule_Homing|Homing Module",
    };

    const auto seeds =
    {
        "BerrySeeds|Berry Seeds",
        "LettuceSeeds|Lettuce Seeds",
        "TomatoSeeds|Tomato Seeds",
        "WheatSeeds|Wheat Seeds",
    };
	
	const auto implants =
    {
        "PalPassiveSkillChange_Consumable_WorldTree_ATK|Disposable Implant: Double-Edged Holy Sword",
		"PalPassiveSkillChange_Consumable_WorldTree_DEF|Disposable Implant: Sacred Flesh",
		"PalPassiveSkillChange_Consumable_WorldTree_CraftSpeed|Disposable Implant: Demonic Grasp",
		"PalPassiveSkillChange_Consumable_WorldTree_FullStomach|Disposable Implant: World Tree's Bounty",
		"PalPassiveSkillChange_Consumable_WorldTree_Sanity|Disposable Implant: Hermit",
		"PalPassiveSkillChange_Consumable_WorldTree_MoveSpeed|Disposable Implant: Dimensional Leap",
		"PalPassiveSkillChange_Consumable_WorldTree_ATK_DEF|Disposable Implant: God of Destruction",
		"PalPassiveSkillChange_Consumable_MutationPal_Immortal|Disposable Implant: Immortality",
		"PalPassiveSkillChange_Consumable_MutationPal_Mutant|Disposable Implant: Idiosyncratic",
		"PalPassiveSkillChange_Consumable_MutationPal_Babysitter|Disposable Implant: Babysitter",
		"PalPassiveSkillChange_Consumable_MutationPal_ExplosionResist|Disposable Implant: Heavily Armored",
		"PalPassiveSkillChange_Consumable_RideJumpCount_Increase2|Disposable Implant: Skymarcher",
		"PalPassiveSkillChange_Consumable_CraftSpeed_up3|Disposable Implant: Remarkable Craftsmanship",
		"PalPassiveSkillChange_Consumable_Deffence_up3|Disposable Implant: Diamond Body",
		"PalPassiveSkillChange_Consumable_PAL_ALLAttack_up3|Disposable Implant: Demon God",
		"PalPassiveSkillChange_Consumable_PAL_FullStomach_Down_3|Disposable Implant: Mastery of Fasting",
		"PalPassiveSkillChange_Consumable_PAL_Sanity_Down_3|Disposable Implant: Heart of the Immovable King",
		"PalPassiveSkillChange_Consumable_MoveSpeed_up_3|Disposable Implant: Swift",
		"PalPassiveSkillChange_Consumable_Stamina_Up_3|Disposable Implant: Eternal Engine",
		"PalPassiveSkillChange_Consumable_Vampire|Disposable Implant: Vampiric",
		"PalPassiveSkillChange_Consumable_SwimSpeed_up_3|Disposable Implant: King of the Waves",
    };

    const auto tools =
    {
        "Shield_01|Common Shield",
        "TreasureBoxKey01|Copper Key",
        "Glider_Super|Giga Glider",
        "Shield_03|Giga Shield",
        "TreasureBoxKey03|Golden Key",
        "Glider_Legendary|HyperGlider",
        "Lantern|Hip Lantern",
        "Shield_04|HyperShield",
        "Torch|Hand-held Torch",
        "Axe_Tier_01|Metal Ax",
        "Pickaxe_Tier_01|Metal Pickaxe",
        "Glider_Good|Mega Glider",
        "Shield_02|Mega Shield",
        "MeatCutterKnife|Meat Cleaver",
        "Glider_Old|Normal Parachute",
        "Axe_Tier_02|Refined Metal Ax",
        "Pickaxe_Tier_02|Refined Metal Pickaxe",
        "RepairKit|Repair Kit",
        "Axe_Tier_00|Stone Ax",
        "Pickaxe_Tier_00|Stone Pickaxe",
        "TreasureBoxKey02|Silver Key"
    };

    const auto weapons =
    {
        "AssaultRifle_Default1|Assault Rifle(Common)",
        "AssaultRifle_Default2|Assault Rifle(Uncommon)",
        "AssaultRifle_Default3|Assault Rifle(Rare)",
        "AssaultRifle_Default4|Assault Rifle(Epic)",
        "AssaultRifle_Default5|Assault Rifle(Legendary)",
        "Bat2|Bat",
        "Spear_SoldierBee|Beegarde's Spear",
        "BowGun|Crossbow(Common)",
        "BowGun_2|Crossbow(Uncommon)",
        "BowGun_3|Crossbow(Rare)",
        "BowGun_4|Crossbow(Epic)",
        "BowGun_5|Crossbow(Legendary)",
        "DecalGun_1|Decal Gun 1",
        "DecalGun_2|Decal Gun 2",
        "DecalGun_3|Decal Gun 3",
        "DecalGun_4|Decal Gun 4",
        "DecalGun_5|Decal Gun 5",
        "DoubleBarrelShotgun|Double-barreled Shotgun",
        "Spear_QueenBee|Elizabee's Staff",
        "BowGun_Fire|Fire Arrow Crossbow",
        "Bow_Fifth|Five Shot Bow",
        "Bow_Fire|Fire Bow",
        "FragGrenade|Frag Grenade",
        "GrapplingGun|Grappling Gun",
        "GrapplingGun2|Mega Grappling Gun",
        "GrapplingGun3|Giga Grappling Gun",
        "GrapplingGun4|Hyper Grappling Gun",
        "HomingSphereLauncher|Homing Sphere Launcher",
        "FragGrenade_Fire|Incendiary Grenade",
        "FragGrenade_Ice|Ice Grenade",
        "MakeshiftHandgun|Inferior Handgun",
        "LaserRifle|Laser Rifle",
        "Spear_ForestBoss|Lily's Spear",
        "Musket|Musket",
        "Spear_2|Metal Spear",
        "WeakerBow|Old Bow(Common)",
        "WeakerBow_2|Old Bow(Uncommon)",
        "WeakerBow_3|Old Bow(Rare)",
        "WeakerBow_4|Old Bow(Epic)",
        "WeakerBow_5|Old Bow(Legendary)",
        "BowGun_Poison|Poison Arrow Crossbow",
        "Bow_Poison|Poison Bow",
        "HandGun_Default|Pistol(Common)",
        "HandGun_Default_2|Pistol(Uncommon)",
        "HandGun_Default_3|Pistol(Rare)",
        "HandGun_Default_4|Pistol(Epic)",
        "HandGun_Default_5|Pistol(Legendary)",
        "PumpActionShotgun|Pump Action Shotgun(Common)",
        "PumpActionShotgun_2|Pump Action Shotgun(Uncommon)",
        "PumpActionShotgun_3|Pump Action Shotgun(Rare)",
        "PumpActionShotgun_4|Pump Action Shotgun(Epic)",
        "PumpActionShotgun_5|Pump Action Shotgun(Legendary)",
        "Launcher_Default|Rocket Launcher(Common)",
        "Launcher_Default_2|Rocket Launcher(Uncommon)",
        "Launcher_Default_3|Rocket Launcher(Rare)",
        "Launcher_Default_4|Rocket Launcher(Epic)",
        "Launcher_Default_5|Rocket Launcher(Legendary)",
        "RecurveBow|RecurveBow",
        "Spear_3|Refined Metal Spear",
        "FragGrenade_Elec|Shock Grenade",
        "ElecBaton|Stun Baton",
        "SingleShotRifle|Single-shot Rifle",
        "SniperRifle_Default|Sniper Rifle",
        "Spear|Stone Spear",
        "SphereLauncher|Scatter Sphere Launcher",
        "SphereLauncher_Once|Single-shot Sphere Launcher",
        "Sword|Sword",
        "Bow_triple|Triple Shot Bow",
        "Bat|Wooden Club",
    };

    const auto money =
    {
        "Diamond|Diamond",
        "Eemerald|Emerald",
        "Money|Gold Coin",
        "Quartz|Pure Quartz",
        "Ruby|Ruby",
        "Sapphire|Sapphire"
    };
	
	const auto ancientrelics =
    {
        "WorldTreeRelic_01|Decayed Ancient Relic",
		"WorldTreeRelic_02|Dormant Ancient Relic",
		"WorldTreeRelic_03|Gorgeous Ancient Relic",
		"WorldTreeRelic_04|Glowing Ancient Relic",
		"WorldTreeRelic_05|Glistening Ancient Relic",
		"WorldTreeHolyWater|World Tree Holy Water",
    };
	
		const auto versiononelaunchadditions =
    {
        "Supplement|Nutrient Tonic",
		"Accessory_defense_1|Defense Pendant",
		"Accessory_darkresist_1|Ring of Dark Resistance",
		"Accessory_NeutralSupport|Neutral Support Whistle",
		"Accessory_EXP|Growth Acceleration Bell",
		"Accessory_Dogen|Dogen Emblem",
		"Accessory_Silvegis|Silvegis Emblem",
		"Accessory_Salesman|Wandering Merchant Charm",
		"Accessory_Vanguard|Vanguard Charm",
		"Accessory_ExplosionResist|Explosion-Resistant Undershirt",
		"Accessory_WarsectTerra|Warsect Terra's Belt",
		"Accessory_Toolbelt|Islander's Tool Belt",
		"Accessory_NormalBaton|Celestial Emperor's Baton",
		"Accessory_FireBaton|Flame Emperor's Baton",
		"Accessory_WaterBaton|Lord of the Seas' Baton",
		"Accessory_ElectricBaton|Lord of Lightnings' Baton",
		"Accessory_GrassBaton|Spirit Emperor's Baton",
		"Accessory_IceBaton|Ice Emperor's Baton",
		"Accessory_GroundBaton|Earth Emperor's Baton",
		"Accessory_DarkBaton|Lord of the Underworld's Baton",
		"Accessory_DragonBaton|Divine Dragon's Baton",
		"Accessory_AirWalker_1|Air Walker Mk I",
		"Accessory_AirWalker_2|Air Walker Mk II",
		"Accessory_AirWalker_3|Air Walker Mk III",
		"Accessory_AirWalker_EX|Air Walker EX",
		"Accessory_Hartaliss|Hartaliss Talisman",
		"Otomo_DFFire_ElementBoost_1|Blazamut's Talisman",
		"Otomo_DFWater_ElementBoost_1|Neptilius's Talisman",
		"Otomo_DFElectric_ElementBoost_1|Orserk's Talisman",
		"Otomo_DFLeaf_ElementBoost_1|Lyleen's Talisman",
		"Otomo_DFIce_ElementBoost_1|Frostallion's Talisman",
		"Otomo_DFEarth_ElementBoost_1|Anubis's Talisman",
		"Otomo_DFDark_ElementBoost_1|Lyleen Noct's Talisman",
		"Accessory_Reptyro|Reptyro Charm",
		"Accessory_Wumpo|Wumpo Charm",
		"Accessory_Blazehowl|Blazehowl Ring",
		"Accessory_FalerisAqua|Faleris Aqua Ring",
		"Accessory_FenglopeLux|Fenglope Lux Ring",
		"Accessory_MenastingTerra|Menasting Terra Ring",
		"Accessory_Vaelet|Vaelet Ring",
		"Accessory_Katress|Katress Ring",
		"Accessory_Elphidran|Elphidran Ring",
		"Accessory_Cryolinx|Cryolinx Ring",
		"Accessory_Faleris|Faleris Ring",
		"Accessory_Trust|Ring of Trust",
		"Accessory_Phantom|Phantom Ring",
		"Otomo_DFDragon_ElementBoost_1|Jetragon's Talisman",
		"Armor_LightAncient|Lightweight Ancient Armor",
		"Armor_ColdAncient|Cold-Resistant Ancient Armor",
		"Armor_HeatAncient|Heat-Resistant Ancient Armor",
		"Armor_Ancient|Ancient Armor",
		"Helmet_Ancient|Ancient Helm",
		"Glider_WingPack|Wing Pack",
		"Glider_WingCell|Wing Cell",
		"Weapon_PlasmaCutter|Plasma Multicutter",
		"Weapon_MechanicalBow|Mechanical Bow",
		"Weapon_CombatSMG|Combat SMG",
		"Weapon_PrototypeShotgun|Prototype Shotgun",
		"Weapon_HeavyAssaultRifle|Heavy Assault Rifle",
		"Weapon_TacticalGrenadeLauncher|Tactical Grenade Launcher",
		"Weapon_LaserSword|Laser Sword",
		"Weapon_BeamScatter|Beam Scatter",
		"Weapon_DroneLauncher|Drone Launcher",
		"Weapon_PlasmaRifle|Plasma Rifle",
		"Weapon_BeamLauncher|Beam Launcher",
		"Weapon_PrimitiveSword|Primitive Sword",
		"Weapon_MetalBat|Metal Bat",
		"Weapon_LilySpear_Enhanced|Enhanced Lily's Spear",
    };
	
	// ============================================================
    // SPHERE MODULES (new 1.0 category)
    // ============================================================
    const auto spheremodules =
    {
        "SphereModule_Heavy|Heavy Weight Module",
        "SphereModule_Curve|Curve Module",
        "SphereModule_Spiper|Sniper Module",          // icon asset itself is misspelled "Spiper" - verify in-game
        "SphereModule_Curve2|Slider Module",
        "SphereModule_Sniper2|Sniper Module II",
        "SphereModule_Homing|Homing Module",
    };

    // ============================================================
    // NEW WEAPONS (1.0 content)
    // ============================================================
    const auto newweapons =
    {
        "MetalDetector|Metal Detector",
        "FlameThrower_Default|Flamethrower",
        "GrenadeLauncher|Grenade Launcher",
        "GuidedMissileLauncher|Guided Missile Launcher",
        "MultiGuidedMissileLauncher|Multi Guided Missile Launcher",
        "GatlingGun|Gatling Gun",
        "LaserGatlingGun|Laser Gatling Gun",
        "EnergyRocketLauncher|Plasma Cannon",
        "SemiAutoShotgun|Semi-Auto Shotgun",
        "OldRevolver|Old Revolver",
        "MakeshiftAssaultRifle|Makeshift Assault Rifle",
        "SemiAutoRifle|Semi-Auto Rifle",
        "MakeshiftSubmachineGun|Makeshift SMG",
        "SubmachineGun|SMG",
        "MakeshiftShotgun|Makeshift Shotgun",
        "CompoundBow|Compound Bow",
        "EnergyShotgun|Energy Shotgun",
        "OverheatRifle|Overheat Rifle",
        "SFBow|Advanced Bow",
        "ChargeLaserRifle|Charge Rifle",
        "Katana|Katana",
        "BeamSword|Beam Sword",
        // Terraria-collab weapons (Tides of Terraria event set)
        "YakushimaBlade002|Terra Blade",
        "YakushimaBlade003|Terraprisma",
        "YakushimaGun001|Vortex Beater",
        "YakushimaLantern001|Nightglow",
        "YakushimaBlade004|Excalibur",
        "YakushimaBlade005|Legendary Meowmere",
    };

    // ============================================================
    // NEW ACCESSORIES (1.0 content)
    // Tier suffixes (+1/+2) NOT included below - I only have confirmed
    // base-tier (tier 1) IDs from icon names. See notes at the end.
    // ============================================================
    const auto newaccessories =
    {
        "Accessory_Nonkilling|Ring of Mercy",
        "Accessory_TalentChecker|Ability Glasses",
        "Accessory_HeatColdResist_1|Multiclimate Undershirt",
        "Accessory_MaxWeightUp|Ring of Freight",
        "Accessory_JumpPower_Increase|Anti-Gravity Belt",
        "Accessory_JumpCount_Increase|Double Jump Boots",
        "Accessory_AirDash|Air Dash Boots",
        "Accessory_Otomo_ElementBoost_Normal|Neutral Support Whistle",
        "Accessory_Otomo_ElementBoost_Fire|Fire Support Whistle",
        "Accessory_Otomo_ElementBoost_Water|Water Support Whistle",
        "Accessory_Otomo_ElementBoost_Electricity|Electric Support Whistle",
        "Accessory_Otomo_ElementBoost_Leaf|Grass Support Whistle",
        "Accessory_Otomo_ElementBoost_Ice|Ice Support Whistle",
        "Accessory_Otomo_ElementBoost_Earth|Ground Support Whistle",
        "Accessory_Otomo_ElementBoost_Dark|Dark Support Whistle",
        "Accessory_Otomo_ElementBoost_Dragon|Dragon Support Whistle",
        "Accessory_Otomo_Attack_up|Attack Support Whistle",
        "Accessory_Otomo_Defense_up|Defense Support Whistle",
        "GasMask|Gas Mask",                             // uncertain - uses a stock icon pack, not the usual Accessory_ convention
        "NightVisionGoggles|Night Vision Goggles",      // uncertain - same as above
		"Accessory_HeatColdResist_2|Multiclimate Undershirt +1",
        "Accessory_HeatColdResist_3|Multiclimate Undershirt +2",
        "Accessory_MaxWeightUp_2|Ring of Freight +1",
        "Accessory_MaxWeightUp_3|Ring of Freight +2",
        "Accessory_Otomo_ElementBoost_Normal_2|Neutral Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Normal_3|Neutral Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Fire_2|Fire Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Fire_3|Fire Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Water_2|Water Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Water_3|Water Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Electricity_2|Electric Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Electricity_3|Electric Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Leaf_2|Grass Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Leaf_3|Grass Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Ice_2|Ice Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Ice_3|Ice Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Earth_2|Ground Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Earth_3|Ground Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Dark_2|Dark Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Dark_3|Dark Support Whistle +2",
        "Accessory_Otomo_ElementBoost_Dragon_2|Dragon Support Whistle +1",
        "Accessory_Otomo_ElementBoost_Dragon_3|Dragon Support Whistle +2",
        "Accessory_Otomo_Attack_up_2|Attack Support Whistle +1",
        "Accessory_Otomo_Attack_up_3|Attack Support Whistle +2",
        "Accessory_Otomo_Defense_up_2|Defense Support Whistle +1",
        "Accessory_Otomo_Defense_up_3|Defense Support Whistle +2",
        // Jump/Dash boots: base tier I already listed IS the "+1" name on paldb
        // (e.g. "Double Jump Boots" = tier 1). These are the higher tiers:
        "Accessory_JumpCount_Increase_2|Triple Jump Boots",
        "Accessory_JumpCount_Increase_3|Quadruple Jump Boots",
        "Accessory_AirDash_2|Double Air Dash Boots",
        "Accessory_AirDash_3|Triple Air Dash Boots",
        "Accessory_AirDash_4|Quadruple Air Dash Boots",
		"GasMask|Gas Mask",
		"NightVisionGoggles|Night Vision Goggles",
    };

    // ============================================================
    // NEW MATERIALS (1.0 content)
    // ============================================================
    const auto newmaterials =
    {
        "Processed_Wood|Wooden Board",
        "HighGrade_Processed_Wood|High Quality Wooden Board",
        "Wood_Fine|Hardwood",
        "Wood_WorldTree|Mythical Wood",
        "Plastic|Plasteel",
        "Computer|Computer",
        "AIcore|AI Core",
        "Bio_Coolant|Cryogenic Coolant",
        "Bio_Battery|Bio Battery",
        "Thermal_Core|Thermal Core",
        "Corrosive_Solvent|Corrosive Solvent",
        "AncientParts2|Ancient Civilization Core",
        "Chromium|Chromite",
        "StainlessSteel|Hexolite",
        "RainbowCrystal|Hexolite Quartz",
        "NightStone|Nightstar Sand",
        "PalDarkParts|Dark Fragment",
        "ManganeseOre|Coralum Ore",
        "ManganeseIngot|Coralum Ingot",
        "SkyislandIngot|Soralite Ingot",
        "WorldTreeIngot|Paloxite Ingot",
        "Lotus_hp_01|Life Lotus (S)",
        "Lotus_stamina_01|Stamina Lotus (S)",
        "Lotus_attack_01|Power Lotus (S)",
        "Lotus_workspeed_01|Speed Lotus (S)",
        "Lotus_weight_01|Carrying Lotus (S)",
        "Lotus_hp_02|Life Lotus (L)",
        "Lotus_stamina_02|Stamina Lotus (L)",
        "Lotus_attack_02|Power Lotus (L)",
        "Lotus_workspeed_02|Speed Lotus (L)",
        "Lotus_weight_02|Carrying Lotus (L)",
        "MeteorDrop|Meteorite Fragment",
        "DogCoin|Dog Coin",
        "PalUpgradeStone4|Giant Pal Soul",
        "AncientParts3|Ancient Pal Manuscript",
        "PredatorCrystal|Predator Core",
        "Jewelry_BattleTicket|Battle Ticket",
        "YakushimaIngot001|Hallowed Bar",
        "PalAwakening_Material_Water|Water Radiant Gem",
        "PalAwakening_Material_Electric|Electric Radiant Gem",
        "PalAwakening_Material_Ground|Ground Radiant Gem",
        "PalAwakening_Material_Grass|Grass Radiant Gem",
        "PalAwakening_Material_Fire|Fire Radiant Gem",
        "PalAwakening_Material_Ice|Ice Radiant Gem",
        "PalAwakening_Material_Dragon|Dragon Radiant Gem",
        "PalAwakening_Material_Dark|Dark Radiant Gem",
        "PalAwakening_Material_Neutral|Neutral Radiant Gem",
        "PalItem_PinkRabbit|Ribbuny Ribbon",
        "PalItem_MopBaby|Swee Hair",
        "PalItem_NegativeOctopus|Killamari Tentacle",
        "PalItem_RaijinDaughter|Dazzi Cloud",
        "PalItem_LizardMan|Leezpunk Crest",
        "Jewelry_BountyProof_1|Successful Bounty Token",  // uncertain icon-pack convention, verify
		"PalEgg_WorldTree_01|Ominous Egg",
        "PalEgg_WorldTree_02|Ominous Egg (2)",
        "PalEgg_WorldTree_03|Large Ominous Egg",
        "PalEgg_WorldTree_04|Large Ominous Egg (2)",
        "PalEgg_WorldTree_05|Huge Ominous Egg",
		"Jewelry_BountyProof_1|Successful Bounty Token"
    };

    // ============================================================
    // NEW AMMO (1.0 content)
    // ============================================================
    const auto newammo =
    {
        "FlamethrowerBullet|Flamethrower Fuel",
        "MissileBullet|Missile Ammo",
        "GrenadeBullet|Grenade Ammo",
        "GatlingBullet|Gatling Gun Ammo",
        "MeteorBullet|Meteorite Ammo",
        "EnergyLauncherBullet|Plasma Cartridge",
        "LaserGatlingBullet|Laser Gatling Cartridge",
        "ReinforcedArrow|Reinforced Arrow",
        "SFArrow|Advanced Arrow",
        "ChargeLaserRifleBullet|Charge Rifle Ammo",
        "OverheatRifleBullet|Overheat Rifle Ammo",
        "EnergyShotgunBullet|Energy Shotgun Ammo",
        "PalDopingShotBullet|Boost Gun Ammo",
    };

    // ============================================================
    // NEW GLIDERS (1.0 content)
    // ============================================================
    const auto newgliders =
    {
        "WingGlider|Wing Pack",
        // "Hyper Glider" deliberately omitted - its icon is shared with the
        // existing "Glider_Legendary" entry, but Hyper Glider and
        // Glider_Legendary have different stats on paldb, so they can't share
        // an ID. Actual ID unknown - verify in-game before adding.
    };

    // ============================================================
    // NEW KEY ITEMS (non-saddle only - saddles require owning that Pal)
    // ============================================================
    const auto newkeyitems =
    {
        "AdditionalInventory_001|Small Pouch",
        "AdditionalInventory_002|Medium Pouch",
        "AdditionalInventory_003|Large Pouch",
        "AdditionalInventory_004|Giant Pouch",
        "Unlock_Picking|Lockpicking Tool v1",
        "Unlock_Picking_Tier2|Lockpicking Tool v2",
        "Unlock_Picking_Tier3|Lockpicking Tool v3",
        "UnlockEquipmentSlot_Accessory|Mysterious Accessory Box",
        "UnlockEquipmentSlot_Accessory_1|Box of Mystery Accessories",
    };
	
}